version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      [
        "start-dev",
        "--db=postgres",
        "--db-url-host=postgres",
        "--db-username=postgres",
        "--db-password=password",
        "--db-url-database=keycloak",
        "--hostname=localhost"
      ]

volumes:
  postgres_data:
