version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    command:
      [
        "start-dev",
        "--db=postgres",
        "--db-url-host=host.docker.internal",
        "--db-username=postgres",
        "--db-password=password",
        "--db-url-database=keycloak",
        "--hostname=localhost"
      ]