spring:
  application.name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          # You can specify either jwk-set-uri or issuer-uri
          jwk-set-uri: ${JWT_SET_URI}
          issuer-uri: ${ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          ${CLIENT_ID}:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid
server.port: 8081